### ISSUE TITLE
Ensure Google Cloud Storage API Change Compatability / July 1st 2021

### ISSUE THREAD

**Issue by rubillionaire** [risd/webhook-server-open#8]
> What do I need to know?

> Currently, Cloud Storage allows "doubly compressed" objects (that is, objects that are gzip-compressed but also have an underlying Content-Type that is itself compressed, such as a jpeg file) to be uploaded and stored, but it does not allow objects to be served in a doubly compressed state unless the object's Cache-Control metadata includes no-transform.

> Cloud Storage currently automatically removes the outer, gzip, level of compression, drops the Content-Encoding response header, and serves the resulting object. This occurs even for requests with Accept-Encoding: gzip. Thus the file that is received by the client does not have the same checksum as what was uploaded and stored in Cloud Storage, so any integrity checks fail.

> After July 1, 2021, the following header will always be respected and return objects, including doubly-compressed objects, as-they-are-stored, without automatically decompressing:

>    Accept-Encoding: gzip

> This will allow for client-side checksum validation when retrieving Cloud Storage objects that are in this doubly-compressed state.
What do I need to do?

> If you're using an off-the-shelf HTTP solution you should not be impacted and no action is required on your part.

> Until July 1, 2021, you will not be able to request a doubly-compressed object as-it-is-stored using Accept-Encoding: gzip. In order to validate that your HTTP client handles cases as expected, we provide you with two test cases that simulate a before and after result using a compressed text file (which will not change behavior).

> Note: The following test cases use a compressed text file as an example to simulate what Cloud Storage will support for doubly-compressed objects once this change takes effect.

> Test Case 1: Simulate current behavior of doubly-compressed object download

>    URL: https://storage.googleapis.com/object-transcoding/readable.txt.gz
>    Expected crc32c of downloaded object: dBQkOg==
>    Expected result: Cloud Storage returns text "Simple text file"

>Test Case 2: Simulate updated behavior of doubly-compressed object download

>    URL: https://storage.googleapis.com/object-transcoding/readable.txt.gz
>    Headers: Accept-Encoding: gzip
>    Expected crc32c of downloaded object: ozNnqA==
>    Expected result: Cloud Storage returns gzip compressed object

> Calculate crc32c of a file with gsutil

>    gsutil hash ./local-file.txt

> If your existing requesting client can successfully handle and complete the test cases outlined in the above section, no further action is required on your part.

**Comment by rubillionaire** [comment]
i have done an audit of the entire code base and have added some tests to this repo that ensure our cloud storage usages is in compliance with the latest changes.

everything has been merged into master as v1.1.10, and all tests are passing.

i will deploy these changes into production today.

**Comment by room421** [comment]
@rubillionaire Excellent. Thanks!

**Comment by rubillionaire** [comment]
no problem, @room421 

this has been deployed and we are all set for the upcoming cloud storage changes.
